Translations update from Weblate
otacke/h5p-ar-scavenger pull request #10
Opened 2021-08-27 13:55 UTC by translate-h5p

Translations update from [Weblate](https://translate-h5p.tk/weblate/projects/h5p/h5p-ar-scavenger/) for H5P/h5p-ar-scavenger.

Current translation status:

![Weblate translation status](https://translate-h5p.tk/weblate/widgets/h5p/-/h5p-ar-scavenger/horizontal-auto.svg)

2021-08-27 23:40 UTC, otacke requested changes

2021-08-27 23:40 UTC, otacke commented on language/es-mx.json
> +                  {
lines 159-162 are redundant and lead to mismatch with .en.json

2021-08-27 23:40 UTC, otacke commented on language/es.json
> +                  {
lines 159-162 are redundant and lead to mismatch with .en.json

2021-08-27 23:40 UTC, otacke commented on language/th.json
> +{
This file has severe mismatches with .en.json.

2021-08-28 16:12 UTC, sr258 commented
Sorry about that. Not sure why Weblate didn't detect the structural change in .en.json. It's possibly caused by the empty object...

It's also very strange that the Thai structure was completely wrong. Was there a recent big change to .en.json?

2021-08-28 18:49 UTC, otacke commented
@sr258 Nothing to worry about! Yes, I moved some properties higher up in the hierarchy and added some others lately.

2021-08-28 18:54 UTC, otacke approved these changes
Excellent! Thanks!

To avoid issues, it might be better not to use the master branch - at least for those content types that have not yet been officially released. I may not always update all the translation files /the template at once when developing, and actually having translations at that stage makes developing harder as I'll have to take care of them instead of inviting translations when the content type is "done"

2021-08-28 18:54 UTC, merged

2021-08-28 19:27 UTC, sr258 commented
The problem is that if I use the release branch instead, PRs will also target the release branch.

2021-08-28 20:02 UTC, otacke commented
Ah. I see. That's unfortunate indeed.